### ISSUE TITLE
Can't release microphone after leave stage

### ISSUE THREAD

**Issue by isaacchiang-kkstream** [aws-samples/amazon-ivs-multi-host-for-android-demo#1]
I use below code to list device and set the "publishStreams" into Stage Strategy. When i leave the stage, i can see the camera notification disappear because i detach ImagePreviewView from it's parent. But the audio notification is still on the status bar, like the microphone didn't release. I try to set "AudioLocalStageStream" and "AudioDevice" to null, this issue is still exist. How can i release the audio device if i leave the stage?

SDK version: 'com.amazonaws:ivs-broadcast:1.9.0:stages@aar'

```
private fun initLocalVideoAndAudioDevice(): ArrayList<LocalStageStream> {
        val publishStreams = arrayListOf<LocalStageStream>()
        val deviceDiscovery = DeviceDiscovery(context)
        val devices = deviceDiscovery.listLocalDevices()

        for (device in devices) {
            val desc = device.descriptor
            if (cameraDevice == null && desc.type == Device.Descriptor.DeviceType.CAMERA && desc.position == Device.Descriptor.Position.FRONT) {
                cameraDevice = device
            }
            if (micDevice == null && desc.type == Device.Descriptor.DeviceType.MICROPHONE) {
                micDevice = device as AudioDevice
            }
        }

        cameraDevice?.let {
            ImageLocalStageStream(it).apply {
                videoStream = this
            }
        }?.also {
            publishStreams.add(it)
        }

        micDevice?.let {
            AudioLocalStageStream(it).apply {
                microphoneStream = this
            }
        }?.also {
            publishStreams.add(it)
        }

        return publishStreams
    }
```

**Comment by rameshvoltella** [comment]
if you're using DeviceDiscovery to get the devices, try using [DeviceDiscovery.release()](https://aws.github.io/amazon-ivs-broadcast-docs/1.13.2/android/com/amazonaws/ivs/broadcast/DeviceDiscovery.html#release()).
